sudo: false

language: node_js

node_js:
  - "stable"

cache:
  directories:
  -"node_modules":

before_script:
  - cd v1

script:
  - npm test

after_success: npm run coverage

notifications:
  email: false